### ISSUE TITLE
Ensure hamburger menu links work

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1005]
Currently the hamburger/header links aren't working. i.e. About, Contact, etc

**Comment by kdondziak** [comment]
@johnhbenetech As far as I know, we never had Contact page. On about us page there is contact section. Can you give details about these pages?

**Comment by johnhbenetech** [comment]
@kdondziak contact should be a mailto: like on the footer of the current homepage

**Comment by abaranowska1** [comment]
@jkondrat I found one issue with hamburger links. When I click links in order: Home, About, Contact, Settings, Password, Sign Out I have a problem with displaying Password page ( Homepage is displayed instead of Password ), the same issue exists when I want to go from Password to Settings. It is possible only when I click for example About, Settings, About, Password.
![Peek 2020-05-21 11-08](https://user-images.githubusercontent.com/61964176/82544670-c3ef8080-9b55-11ea-80fc-b548f6f515e9.gif)

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified cases:** 

- All links work without any problems on mobile view. 
![Peek 2020-05-22 09-46](https://user-images.githubusercontent.com/61964176/82645483-3a05ed00-9c13-11ea-872f-b078de13704b.gif)
