### ISSUE TITLE
Add filtering to all records section

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1007]
This task involves setting up the initial filtering infrastructure on the homepage. Similar to #1006 these filters should NOT affect the top "your records" portion.

This filter shade should slide in from the right on desktop (responsively flexing the cards so that none are hidden by the shade). On mobile it should appear in a modal similar to how sort appears.

For the first iteration we will include the following:
* City
* County
* Zip
* Service Type (taxonomy)

The modal/shade should have apply and clear buttons at the bottom. Ideally all of these inputs will have autocompletes that reflect the available values from ONLY the Service Provider records (similar to the approach in the old UI).

General mockup:
![filter shade mockup](https://user-images.githubusercontent.com/12927553/82383130-d2715700-99f2-11ea-9e38-966f5b3100f3.png)

**Comment by kdondziak** [comment]
@johnhbenetech I want to confirm. After clicking on filter button, cards should width should decrease or they should change their position to make place for filter section?

**Comment by kdondziak** [comment]
@johnhbenetech On mock zip is text input and on old app there is select(dropdown) with zip codes. Which one it should be?

**Comment by johnhbenetech** [comment]
@kdondziak for positioning, option 2. Let me know if that's particularly difficult and we can discuss. 

And zip should be a drop-down

Also just to confirm, are we currently running geocoding on these records, or will I need to make another task for that as well?

**Comment by kdondziak** [comment]
@johnhbenetech No, I believe geocoding is not involved, if you are asking whether geocoding is used to select which records should be shown.

**Comment by johnhbenetech** [comment]
@kdondziak ok I've made #1008 so that geocode data can be made available for these records in the future.

**Comment by kdondziak** [comment]
@johnhbenetech What is service type? Is that taxonomy? I see that service has type filed, but almost every service have type 'program'.

**Comment by johnhbenetech** [comment]
@kdondziak it's taxonomy

**Comment by abaranowska1** [comment]
@kdondziak 
I found one issue and I have one question
1. After click "Load more" button and use filters - data are not displayed 
![Peek 2020-05-25 09-53](https://user-images.githubusercontent.com/61964176/82793739-b564da00-9e71-11ea-9113-2e28782b58c8.gif)
@johnhbenetech 
2. On Create Organization Page, in Location section, we can see the shortcuts of states 
![Screenshot from 2020-05-25 10-02-26](https://user-images.githubusercontent.com/61964176/82794146-4cca2d00-9e72-11ea-8748-7910d5eac1a0.png)
but in the filtering section, we have the counties in the states
![Screenshot from 2020-05-25 10-03-38](https://user-images.githubusercontent.com/61964176/82794391-b2b6b480-9e72-11ea-86f9-ebc4acf36afd.png)
and I'm not sure if it is correct, because when I used filter Country and picked: Alameda Country I found these two Organizations 
![Selection_395](https://user-images.githubusercontent.com/61964176/82794580-fc9f9a80-9e72-11ea-8058-1a103aa1203a.png)

**Comment by johnhbenetech** [comment]
@abaranowska1 my assumption is that geocoding runs in record creation. The geocoding fills in missing information (such as county)

**Comment by abaranowska1** [comment]
**Tested with success**
**Verified cases:** 
- Add filter options (City, County, Zip, Service Type)
- Filter window displays as @kdondziak mock and also works on mobile without issues
- After click "Load more" button and use filters - data are displayed
- These filters didn't affect the top "your records" portion

![Peek 2020-05-26 10-18](https://user-images.githubusercontent.com/61964176/82879735-acd9d580-9f3d-11ea-80c3-6f92916c803d.gif)

**Verified on:**
- Google Chrome v. 83.0.4103.61
- Firefox v. 76.0.1
- Mobile device 360 x 640
- iPhone X 375 x 812
