### ISSUE TITLE
Improve Map View on mobile.

### ISSUE THREAD

**Issue by awalkowiak** [benetech/ServiceNet#1073]
Improve map view on mobiles (smaller devices) to look a bit more like this:

![](https://user-images.githubusercontent.com/12927553/84964185-10849800-b0d1-11ea-8b7b-f271cf6dafce.png)

**Comment by awalkowiak** [comment]
@johnhbenetech the question popped out. Where would you like to have the navigation button pills (back to "grid view" and "filter")? I suggest having those pills under the search bar with a transparent background (to see more map). But there are other options like having only the grid view button in the same line with search bar or moving these buttons to the side menu.

**Comment by johnhbenetech** [comment]
@awalkowiak I like having them as pills under the search bar. Thanks for pointing it out

**Comment by bognasoldev89** [comment]
@kdondziak I have a few remarks
1. 
As far as I understood, those pills were to be "under the search bar with a transparent background (to see more map)." At this point, those are simply above the map. @johnhbenetech can you clarify, which version is final?
![ServiceNet - Google Chrome_001](https://user-images.githubusercontent.com/51324797/89636051-4dd2fe00-d8a8-11ea-9eab-a4821bbe50ad.png)
2. 
Should the map always zoom out after clicking search/filter pills?
![Peek 2020-08-07 12-15](https://user-images.githubusercontent.com/51324797/89636236-97bbe400-d8a8-11ea-812a-f471ab7f0134.gif)
3.
The user would use some option to discard an organization card from the map view. The user can tap pin on the map, go through the map and change pins, but cannot discard a card to see clear map again.
![Peek 2020-08-07 12-13](https://user-images.githubusercontent.com/51324797/89636344-c639bf00-d8a8-11ea-8591-315ea671a148.gif)

**Comment by johnhbenetech** [comment]
The preference is for them to have transparent background and be on top of map. The reasoning is that if the user scrolls to where the map takes up the whole screen, it can be disorienting and unclear how they should get back to grid view since the buttons are now off the screen.

I totally understand if this is unnecessarily complex to accomplish. I don't want to have to do something hacky to pull it off, so if it's not possible to accomplish let me know.

The maps JS docs refer to some support for custom controls

**Comment by abaranowska1** [comment]
@pmuchowski @kdondziak 
I retested this task and I see that issues from points 2 and 3 are fixed. The map is not zoomed out after clicking Sort or Filter buttons and it is possible to discard just opened card because "x" button is added. 
![image](https://user-images.githubusercontent.com/61964176/90765439-32c1ae80-e2ea-11ea-9f21-85a147d1ce1a.png)

I found a similar issue to point 1, related to white background under pills, but on public view. It looks a little weird so if you can please check what is wrong here. The problem occurs only on public view during scrolling or swiping down, to reproduce you should catch the screen just under the main header with Benetech logo 
![image](https://user-images.githubusercontent.com/61964176/90765973-20944000-e2eb-11ea-91a3-8c5a33ccc164.png)
![Peek 2020-08-20 13-44](https://user-images.githubusercontent.com/61964176/90766128-59ccb000-e2eb-11ea-9df7-e064adc64ea7.gif)

**Comment by abaranowska1** [comment]
**Tested with success**
Confirmed that all issues are fixed and the map view is similar to the mock. 
- Pills are under the search bar with a transparent background
- The map is not zoomed out after clicking Sort or Filter buttons 
- It is possible to discard just opened card via "x" button 
- Map view look that same also on the public view

![Uploading image.png…]()

**Verified on:**
- Ubuntu 18.04
- Google Chrome v.84.0.4147.125
- Mobile 360 x 640
