### ISSUE TITLE
Unknown Error on ServiceProvider record creation

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1102]
I don't know the exact way to reproduce, but it's happened a few times so maybe @abaranowska1 or @bognasoldev89 can try to reproduce.

What I was doing:
* Log in as ServiceProvider
* Start making a new record
* Take a while to make a record, i was looking stuff up on google and copying/pasting info in
* I think i wound up with like 13 locations and maybe 5 services - all with a good amount of information

When I went to click 'I'm Finished' a long-running request was launched, and it stayed on the record creation screen. After about 8 seconds it took me out of the record creation screen. The new page had the same header as our normal site, but the body was just something like 'an unexpected error has occurred'.

Upon refreshing the page, I was back at the normal homepage and the record i was working on had been created successfully and all information was retained. I unfortunately didnt capture the network activity at the time the error occurred, but it does seem from the API side things worked as expected.

From the JS side there is a console log:
![image](https://user-images.githubusercontent.com/12927553/88419145-3d039200-cdaa-11ea-8b9e-f8164eb86799.png)

If you recall we've seen this before. I just wonder if there is some weird race condition or something in the DOM rendering that causes the error screen to be displayed. I'll keep trying to reproduce reliably

**Comment by kdondziak** [comment]
@johnhbenetech I tried to reproduce. Please tell me if it is what you've experienced
![tooltip2](https://user-images.githubusercontent.com/52406204/88537319-a3d4b580-d00d-11ea-9b51-7d50ca7cf30b.gif)

**Comment by bognasoldev89** [comment]
**Tested with success**

**Environment**
- staging env
- browsers
-- Chrome 83.0.4103.116

**Verified cases**
- Opening the user's tooltip on:
-- provider view
-- classic homepage
-- single record view
-- multi record view
-- all records view

**Summary**
Thanks to @kdondziak investigation it turned out the tooltip was responsible for the mentioned error. I checked if tooltips don't provoke errors during using the app.

**Attachments**
![sn 1102 all](https://user-images.githubusercontent.com/51324797/88554706-228a1c80-d027-11ea-8465-7f2646cfb1f2.gif)

![sn 1102 homepage](https://user-images.githubusercontent.com/51324797/88554712-23bb4980-d027-11ea-8277-a30e11ef24df.gif)

![sn 1102 multi](https://user-images.githubusercontent.com/51324797/88554715-2453e000-d027-11ea-908b-d40c206e22f4.gif)

![sn 1102 prov](https://user-images.githubusercontent.com/51324797/88554718-24ec7680-d027-11ea-92ab-cee7923c2fa0.gif)

![sn 1102 single](https://user-images.githubusercontent.com/51324797/88554720-25850d00-d027-11ea-87dc-7a95d5b39936.gif)
