### ISSUE TITLE
Internal Server Error is thrown during deleting shelters from admin view

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#1125]
I noticed that part of the shelters throw Internal Server Error while the user tries to delete them.

**Reproduction**
1. Log in as an admin
2. Open Shelters entity
3. Delete shelter

**Expected result**
4. The shelter is deleted

**Actual result**
4. Internal server error is thrown

**Attachment**
![Peek 2020-08-21 13-33](https://user-images.githubusercontent.com/51324797/90886781-5bfa4180-e3b3-11ea-9be7-6e03b72d37e5.gif)

**Note**
This bug can be connected with disrupted relations, probably beds.

>   "detail" : "could not execute statement; SQL [n/a]; constraint [fk_beds_shelter_id]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement",

**Comment by abaranowska1** [comment]
**Tested with success**
I tried to delete the Shelter from the description and I can do it without any issues. Also I can delete another Shelters so in my opinion the issue was resolved.
![Peek 2020-09-03 15-27](https://user-images.githubusercontent.com/61964176/92121860-0e41f800-edfb-11ea-9493-0e26f4b38115.gif)

**Tested on:**
- Ubuntu 18.04
- Google Chrome v.84.0.4147.135
