### ISSUE TITLE
Adding Hours of operation to ServiceProvider

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1149]
- add the below "hours of operations" table in editing a record under location details 
- ideally, every location they have will have each own hours of operations time list
- when adding locations, a new table should show up for each location a user adds

<img width="320" alt="Screenshot 2020-11-30 154610" src="https://user-images.githubusercontent.com/65787629/100679522-88174e00-3324-11eb-9771-f9130fb7ce85.png">

**service Net theme**
<img width="350" alt="Screenshot 2020-11-30 155604" src="https://user-images.githubusercontent.com/65787629/100679560-97969700-3324-11eb-92a7-3391a0c39f89.png">

Changes on update my record (desktop)
---------------------------
- add below the address

<img width="662" alt="Screenshot 2020-11-30 160906" src="https://user-images.githubusercontent.com/65787629/100680443-661ecb00-3326-11eb-9546-b0c9e93a8ddc.png">

Changes on Tell us where your services are Located in adding a new record (desktop)
--------------------------------
<img width="752" alt="Screenshot 2020-11-30 155352" src="https://user-images.githubusercontent.com/65787629/100679436-5900dc80-3324-11eb-9258-f234e27589cb.png">

Changes on update my record (mobile)
---------------------------
<img width="140" alt="Screenshot 2020-11-30 160515" src="https://user-images.githubusercontent.com/65787629/100680181-db3dd080-3325-11eb-92a1-2f47bcd30b28.png">

Changes on Tell us where your services are Located in adding a new record (mobile)
--------------------------------
<img width="143" alt="Screenshot 2020-11-30 160456" src="https://user-images.githubusercontent.com/65787629/100680153-d1b46880-3325-11eb-9133-71bcf8f9ab97.png">

**Database**
- add hours of operation in the database

**Comment by EnriqueCorado** [comment]
@meenupant

**Comment by johnhbenetech** [comment]
@meenupant @EnriqueCorado What's in the time dropdowns?

Are we sure this should be at the location level and not the service level? What is that assumption based on?

Often times you will see indications of something like a lunch break - e.g. open from 9-12, closed 12-2, open 2-5 - do we want to deal with this case?

**Comment by EnriqueCorado** [comment]
@johnhbenetech under the time dropdowns
<img width="1348" alt="Screenshot 2020-12-03 082152" src="https://user-images.githubusercontent.com/65787629/101057183-9fcb1e00-3540-11eb-9270-40b607bc095d.png">


- I can add them at both levels, just in case for e.g. the redwood city community center opens at 8 am, but legal services open at 9 am and close earlier than the community center 

- I will add lunch breaks. great point

**Comment by EnriqueCorado** [comment]
- please add a text entry field for all the times under Open, Lunch Break, and Close 
- a checkbox column for "Closed" to indicate their services are not offered during those days
- add all changes to the "editing a record" section as well 

Location Level (Desktop)
--------
<img width="895" alt="Screenshot 2020-12-03 083929" src="https://user-images.githubusercontent.com/65787629/101059413-1832de80-3543-11eb-92aa-0c395e85952d.png">


Location Level (mobile)
--------
<img width="155" alt="Screenshot 2020-12-03 084013" src="https://user-images.githubusercontent.com/65787629/101059501-326cbc80-3543-11eb-84a2-218f55313554.png">


Service Level (Desktop)
--------
<img width="673" alt="Screenshot 2020-12-03 084538" src="https://user-images.githubusercontent.com/65787629/101060168-f1c17300-3543-11eb-8e03-be443391c7ab.png">


Service Level (Mobile)
--------
<img width="139" alt="Screenshot 2020-12-03 084116" src="https://user-images.githubusercontent.com/65787629/101059604-5203e500-3543-11eb-96eb-7186d0127fea.png">

**Comment by kkaczmarczyk** [comment]
@EnriqueCorado @meenupant Should this ticket also include logic to parse the non-service provider records (e.g. Eden) records that were claimed?

**Comment by kkaczmarczyk** [comment]
dev note: add fields for date to the OpeningHours entity

**Comment by EnriqueCorado** [comment]
@kkaczmarczyk 
include logic to parse the non-service provider records

**Comment by jkondrat** [comment]
@EnriqueCorado @johnhbenetech : Which design should we use: the one from Enrique's comment or the one in the ticket description?

**Comment by johnhbenetech** [comment]
@jkondrat the one from comment. 

@EnriqueCorado for clarity, please ensure description is updated to always reflect the desired end state

**Comment by abaranowska1** [comment]
@jkondrat 
- "Please pre-populate weekdays from 9:00 AM to 5:00 PM and closed on weekends same for mobile. Second row, with no default settings up" - this is not implemented 
- Please make the fields for time wider, because when we have for example 10:30 PM, "PM" is not visible in the field
![image](https://user-images.githubusercontent.com/61964176/102197004-e1ed4b80-3ec0-11eb-9c89-4b760e275e9e.png)
- An unexpected error occurs during removing the first row, please look at it
![Peek 2020-12-15 10-10](https://user-images.githubusercontent.com/61964176/102197411-663fce80-3ec1-11eb-86e8-9bf9e115b402.gif)
- Mobile UI issues: 
Edit and Create Location page. I think that we should move the days of the week section to the left and center the fields for hours and buttons 
![image](https://user-images.githubusercontent.com/61964176/102197963-1c0b1d00-3ec2-11eb-93b7-05568511f5b0.png)
![image](https://user-images.githubusercontent.com/61964176/102198848-2da0f480-3ec3-11eb-880b-f5c5a4743032.png)
- If possible, please change the "format that others will see" so that the days of the week are displayed, for example, from Sunday to Saturday, and not in the order in which we click on the individual fields with the days of the week
![image](https://user-images.githubusercontent.com/61964176/102203284-af475100-3ec8-11eb-9527-0c23aad0122f.png)
- Time and date format. If we pick the time 8:00 and date 12/03/2022 we should have the same format in the "format that others will see" section, now we can see **0**8:00 and 12/**3**/2022
![image](https://user-images.githubusercontent.com/61964176/102203904-7360bb80-3ec9-11eb-84f0-77e62a31ecea.png)

**Comment by abaranowska1** [comment]
**Tested with success**
- Hours of operation was added to the SP view ( creation and edit Location view )
![image](https://user-images.githubusercontent.com/61964176/102232986-0ad90500-3ef0-11eb-9946-c9a50e5778c5.png)
![image](https://user-images.githubusercontent.com/61964176/102232998-0f9db900-3ef0-11eb-9992-8180d65a8d6a.png)
- We are using default opening hours on weekdays from 9:00 AM to 5:00 PM and closed on weekends
![image](https://user-images.githubusercontent.com/61964176/102233031-188e8a80-3ef0-11eb-8c50-b49b4a4ee690.png)
- Second row, with no default settings up
- Add more and Remove buttons were added 
- UI issues on mobile and web view were fixed
- The "format that others will see" displays days of the week in a row 
- The time and date format now are consistent
- Time field is wider
- Opening hours are also updated in the old view 
![Selection_575](https://user-images.githubusercontent.com/61964176/102232967-04e32400-3ef0-11eb-96ca-1cf8db884a16.png)

**Verified on:**
- Mobile 360x640
- iPhone X
- Google Chrome, Firefox, Safari browsers
- Windows 10, Ubuntu 20.04, Mojave OS

**Comment by meenupant** [comment]
@kkaczmarczyk @abaranowska1 Please check if this is causing errors in adding and updating records.

**Comment by johnhbenetech** [comment]
see #1477 - not sure what root cause might be

**Comment by abaranowska1** [comment]
#1477 fixed
