### ISSUE TITLE
Use static metamodel class in criteria query

### ISSUE THREAD

**Issue by pmuchowski** [benetech/ServiceNet#1164]
Use static metamodel class in criteria query instead of the string constants to improve readability and make the code less error prone.

dev-note: take a look at this article: https://thorben-janssen.com/static-metamodel/

**Comment by jkondrat** [comment]
I tried using metamodels to define fetch graphs in ProviderRecordsRepository, but it seems that it simply generates fetch joins, which results in an error in our case:
Caused by: java.lang.IllegalArgumentException: org.hibernate.QueryException: query specified join fetching, but the owner of the fetched association was not present in the select list

Let's keep the selects as is
