### ISSUE TITLE
CBO Interface: Replace top heading from “HOME ABOUT CONTACT” to “Admin” and “Refer” and “Referral Tracking” 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1169]
Replace top heading from “HOME ABOUT CONTACT” to “Admin” and “Refer” and “Referral Tracking” 
- "Home" click on will simply be replaced to "Admin"
- Keep font from about and contact, the same style, just change the titles  

- **On mobile view**, keep hamburger menu
 - Instead of "Home" just change to  "Admin"
-  add the other two options under "Home" which will now be "Admin", to "Refer", "Referral Tracking"
- Options "About", Contact", "Feedback", "Deactivate Records", "Settings", "Password", and "Sign Out" will go under  
- keep same font, color, underline when clicked option as it currently does 

  
<img width="393" alt="Annotation 2020-09-02 083443" src="https://user-images.githubusercontent.com/65787629/92004517-29c3da80-ecf7-11ea-8dd0-d38081603100.png">

<img width="307" alt="Annotation 2020-09-02 084753" src="https://user-images.githubusercontent.com/65787629/92005998-04d06700-ecf9-11ea-9b8e-8ff62770d1ea.png">

<img width="330" alt="Annotation 2020-09-02 084819" src="https://user-images.githubusercontent.com/65787629/92006021-0f8afc00-ecf9-11ea-942a-5d32c3349b3c.png">

**Comment by johnhbenetech** [comment]
just a note, for any design changes please provide mobile mockups as well. For example in this task we prob want to utilize the existing 'hamburger menu' in the mobile view unless you want these more front and center

**Comment by EnriqueCorado** [comment]
got it. thank you for the heads up

**Comment by johnhbenetech** [comment]
I think one thing to consider here is that there are currently several screens where we might have different designs:
1. Home screen for logged in user
2. Home screen for 'public' unauthenticated users
3. A 'single record' view when a user clicks into a record
4. An 'edit' view when a record owner clicks into their own record

I disagree with the removal of the home link on the single record or edit view for instance, since it's a clear way for the user to go back to all records. Technically speaking they can also click the servicenet logo, but not sure it's as clear.

It also probably doesnt make sense to have the refer links on the edit view since it's your record and you arent gonna make referrals to yourself.

I don't know that I understand the need for the 'Refer' link on the home page or honestly task #1171 in it's entirety. I dont understand the justification for creating a entirely new view that is 95% the same as an existing view? I think the most likely user flow is that the referrer is looking at a single record when they make the referral (because they are making that decision after looking at the info provided). If anything I think we could surface the referral option on each card and/or on the single-record page. I dont know that the navigation menu is the best place for it, and it probably makes more sense to surface it contextually within the page itself.
