### ISSUE TITLE
CBO Refer Page: REMOVE THE RECORD ON REFERRAL PAGE

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1171]
**Computer Access View**
- Once "Refer" click on has been replaced from "About"
- When the user clicks on to refer, the webpage will look like the following 
<img width="1469" alt="Annotation 2020-09-02 092551" src="https://user-images.githubusercontent.com/65787629/92010156-4dd6ea00-ecfe-11ea-80ba-ecc22b4726f9.png">
- Remove add a new record square
- Remove the record created square
- Remove "Any updates to your record"
<img width="1459" alt="Annotation 2020-09-02 092727" src="https://user-images.githubusercontent.com/65787629/92010321-8676c380-ecfe-11ea-9776-278a94c06aa7.png">

**On Mobile**
- It will look like the following 
<img width="263" alt="Annotation 2020-09-02 093018" src="https://user-images.githubusercontent.com/65787629/92010725-fc7b2a80-ecfe-11ea-9697-b21d62efb890.png">

**Comment by johnhbenetech** [comment]
See comments on #1169, copied here:

I don't know that I understand the need for the 'Refer' link on the home page or honestly task #1171 in it's entirety. I dont understand the justification for creating a entirely new view that is 95% the same as an existing view? I think the most likely user flow is that the referrer is looking at a single record when they make the referral (because they are making that decision after looking at the info provided). If anything I think we could surface the referral option on each card and/or on the single-record page. I dont know that the navigation menu is the best place for it, and it probably makes more sense to surface it contextually within the page itself.

**Comment by johnhbenetech** [comment]
Not sure of the status of this or if it should be closed as irrelevant now. i just noticed it wasnt on the product board so im adding it back
