### ISSUE TITLE
Filtering and Search No longer working

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#1194]
Not sure when this broke but none of the filters or search do anything anymore.

**Comment by johnhbenetech** [comment]
It seems to be some weird interaction between the map and the card view.

You can get the filters to work through the following:
* Go to map view
* Access and set filter in map view
* Use the 'search in this area' to refresh the pins
* Now return to grid view

So please investigate why the filters aren't cohesive between map and card view.

Also please have the pins refresh automatically when a filter is applied/cleared.

**Comment by abaranowska1** [comment]
**Tested with success**
I checked filtering, sorting, and searching on traditional SP View and Public SP View. I can confirm that the issue was resolved. 

**Verified cases:** 
- Search bar works as before, it is possible to search:
-- Organization name
-- Service name
-- Service description
-- Eligibility
- Sorting also works as before
- Filtering works fine on Grid View and Map View, it is possible to filter data by: 
-- Service Type
-- Locations
Organization name
-- Service name
-- Service description
-- Eligibility

![Peek 2020-09-09 13-38](https://user-images.githubusercontent.com/61964176/92593729-e098fb00-f2a1-11ea-8bda-ef4a9fba0547.gif)

**Verified on:**
- Traditional and Public SP VIew
- Ubuntu 20.04 OS
- Google Chrome v. 85.0.4183.83
