### ISSUE TITLE
Claim a record 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1446]
The flow will be
- when a user register we will shortlist organizations close to the name that they registered with during the registration 
- once the user gets manually approved by Benetech staff
- User during their first log in will have a pop up that shows records that match the information provided in the registration 
- users can have the ability to claim the ones they will manage 

**New users will initially see this display for a few seconds**
<img width="959" alt="Screenshot 2020-12-02 153713" src="https://user-images.githubusercontent.com/65787629/100945149-8335d400-34b5-11eb-9902-1004e60edf54.png">

**After a few seconds a pop up **
<img width="890" alt="Screenshot 2020-12-02 154954" src="https://user-images.githubusercontent.com/65787629/100945423-0ce5a180-34b6-11eb-9cdf-eb21704a88ed.png">

<img width="892" alt="Screenshot 2020-12-02 155016" src="https://user-images.githubusercontent.com/65787629/100945443-15d67300-34b6-11eb-90e8-f03c56959036.png">

- after users have claimed records, or didn't claim any of the records, they can press done and the records claimed will show up on their records

**Comment by EnriqueCorado** [comment]
@meenupant

**Comment by meenupant** [comment]
@EnriqueCorado What if the records that they should have claimed but do not pop up for some reason (maybe a slight spelling mistake or incorrect location)? We would want them to have another option saying "Did we miss finding your record(s)? Would you like to search your record(s) by either location or organization name?" And another option "Would you like to claim more record(s)?" And once they claim their record(s) then we would want them to review all the data fields one by one and give them an option to either confirm (the correct entries) or modify (the incorrect ones). 
And once they are done with this process, let them preview all the information before final confirmation.
@johnhbenetech Did we miss anything?

**Comment by EnriqueCorado** [comment]
- on users first, log in, they will have the below pop up 
- the records will be pre-populated from the organization name(s) matching records on the service net

<img width="744" alt="Screenshot 2020-12-03 121534" src="https://user-images.githubusercontent.com/65787629/101083040-41626780-3561-11eb-8c21-daaef80454a5.png">


- users will be able to claim those records whom are theirs 
- once the user clicks "Done" those records will appear as any record those for a service provider
<img width="751" alt="Screenshot 2020-12-03 121644" src="https://user-images.githubusercontent.com/65787629/101083218-6bb42500-3561-11eb-8cbc-ac102fc905f9.png">


- after the user has clicked done, a second pop up will appear, granting the user the option to either claim more records or not 
<img width="745" alt="Screenshot 2020-12-03 121744" src="https://user-images.githubusercontent.com/65787629/101083591-9bfbc380-3561-11eb-8836-24377ec67494.png">

**Comment by kkaczmarczyk** [comment]
@EnriqueCorado @meenupant 
1. "in admin please add a place where benetech staff can approve these records claimed" - is there a mock-up for this action? I think we could cover this in a new ticket.
2. How do you see role of "Admin/Benetech staff" - should it have the access to the "Entities" and "User management" screens as a superuser Admin?
3. Will the user have the ability to claim records only on the first login or on the subsequent logins as well? If so - on the subsequent should the pop-up/modal appear after 3 seconds on log-in or should this action be triggered by some button?

**Comment by awalkowiak** [comment]
@johnhbenetech Should we allow claiming non-service provider records (eg. Eden, UWBA, Healthleads and so on)? There might be a risk with overwriting user's editions to the record by jobs/uploads. How we should handle this? Or should we not allow claiming non-service provider records?

**Comment by johnhbenetech** [comment]
@EnriqueCorado @meenupant This isn't correct - there is a problem here if we cant answer basic questions about functionality. If product team isn't clear about what they are asking for, these tasks shouldn't make it to development. If the question being asked isn't clear, it's something that should be discussed in detail on a call potentially.

What is the purpose/user story for this task? What is the intended user flow? What is the benefit of this functionality?

My understanding of the entire point of this task was:

"As a CBO, when I find a record from a partner system (Eden, UWBA, etc.) that represents MY OWN organization - i want to have the ability to 'claim' that record as my own - so that I can correct any errors, add additional information, and manage updates to that record going forward'

So if we dont allow for claiming non-service provider records than what are we doing? Allowing CBOs to claim records from other CBOs? Why would we want two different CBOs to be managing the same record?

On the dev side: i believe the goal here is the following:

* Allow for a CBO user to 'claim' an existing record from a partner DB (eden, uwba, etc)
* When claimed the following happens:
1. The data from partner version is copied into a NEW SP record attached to the logged in user/silo
2. The original partner record gets an indication that it has been replaced by the new CBO version, possibly by adding something like a 'replace_by_organization_id' in the organization_silo linkage

From this point on, only the new CBO-owned version will show in the SP view (for all users/views).

On the backend, the original partner version still exists, and will still be receiving normal data updates from the API jobs - these records are just no longer discoverable through the frontend.

Retaining the linkage is important because in the future we may want to do things like:
* allow a CBO to 'unclaim' a record, and therefore revert to showing the UWBA version
* Surface data updates as in #1452

**Comment by awalkowiak** [comment]
@abaranowska1 Here is the brief summary of what was done.
1. Added modal with records to claim. Records shown are from partner providers (every provider except ServiceProvider) and shown are only records that have not been claimed yet.
2. If the user never did claim action, the modal from the previous point will be shown to him automatically. If the user did claim (or clicked the 'Done' button without selecting any record), then the user can trigger the modal by clicking the 'Claim records' button (i think this one was not requested, but I found it useful).
3. Each claimed record after hitting the 'Done' button is cloned into the ServiceProvider record.
4. After clicking the 'Done' button the user has the option to directly go back to claiming or close the modal.
5. Each claimed record will show up in the carousel with the user's records.
6. Claimed records won't show on the 'Claimed records' modal again (unless someone unclaims a record)
7. Option to unclaim is visible only for claimed records on the record edit page.
8. Unclaim deletes the cloned record and the original is back at the 'claim records' modal.
9. Note: some labels from mocks were adjusted to the current version of the feature.

**Comment by abaranowska1** [comment]
@awalkowiak 
Plz take a look why the Internal Server Error is displayed for example when I want to add the Daily Update and Save changes to this Organization: https://benetechservicenet.org/#/record/f61e812a-53da-404b-bfad-fdfe4e367f8a/edit
![Peek 2020-12-16 14-13](https://user-images.githubusercontent.com/61964176/102353147-f86ed200-3fa8-11eb-8c40-edbcb416faec.gif)
![image](https://user-images.githubusercontent.com/61964176/102353162-fd338600-3fa8-11eb-92e6-0e2637fe04ab.png)

**Comment by abaranowska1** [comment]
**Tested**
Going through the acc :
- Modal with records to claim was added. Records shown are from partner providers (every provider except ServiceProvider) and shown are only records that have not been claimed yet.
![image](https://user-images.githubusercontent.com/61964176/102372689-c2891800-3fbf-11eb-9079-fa6d9b6b1f29.png)
- If the user never did claim action, the modal from the previous point will be shown to him automatically. If the user did claim (or clicked the 'Done' button without selecting any record), then the user can trigger the modal by clicking the 'Claim records' button (i think this one was not requested, but I found it useful).
- Each claimed record after hitting the 'Done' button is cloned into the ServiceProvider record.
![image](https://user-images.githubusercontent.com/61964176/102372660-b735ec80-3fbf-11eb-84ec-ff5b3bf8549d.png)
- After clicking the 'Done' button the user has the option to directly go back to claiming or close the modal.
- Each claimed record will show up in the carousel with the user's records.
![image](https://user-images.githubusercontent.com/61964176/102372774-d6347e80-3fbf-11eb-89b9-4cff58555559.png)
- The functionality was added also for mobile 
![Selection_626](https://user-images.githubusercontent.com/61964176/102372965-02e89600-3fc0-11eb-8681-6b73ce8a5c62.png)
![Selection_625](https://user-images.githubusercontent.com/61964176/102372971-0419c300-3fc0-11eb-9171-e55cd9f1ffde.png)

**Comment by awalkowiak** [comment]
@abaranowska1 all fixed beside the issue with the record you pasted here. Seems like this is caused because the PostalAddress for Location is empty (which should not in the ServiceProvider case). 

@johnhbenetech what do you think about this edge case? Should we create a copy of the physical address into the postal address (and if there is an opposite case, then copy the postal address into a physical address)? Is it ok if this will be handled in a separate ticket?

**Comment by johnhbenetech** [comment]
@awalkowiak I'm not sure I understand, can you provide more details?

Let's say a UWBA record contains 0 locations, or a location with no physical address, or a location with no postal address.

If a Service Provider attempts to claim that record what happens?

**Comment by awalkowiak** [comment]
@johnhbenetech I replied in a slack thread with the same issue.

**Comment by abaranowska1** [comment]
Thanks, @awalkowiak for small fixes to taxonomy and PostalAddress, no there is no ISE and all taxonomies are displayed. I created a separate task for performance issue during claiming more records. #1491

**Comment by meenupant** [comment]
@johnhbenetech @EnriqueCorado @kkaczmarczyk  Right now we are displaying this pop-up message after claim "Please wait for email approval for records claimed".  What happens to the claimed record until it is approved? Does it get displayed as owned records (top right)? I believe we do not make it available for others to claim? We must send the approval email saying that your records are not fully claimed until you review and update the missing required information? And shall we put a timeline for the records to be reviewed? We can display this warning sign for the claimed records but with missing required information. Does this make sense? What do you all recommend?
![Screen Shot 2020-12-18 at 8 28 59 AM](https://user-images.githubusercontent.com/74263963/102637603-18b6a200-410b-11eb-9248-54bef93f5060.png)

**Comment by EnriqueCorado** [comment]
@meenupant #1487 goes into the middle step of this process.

**Comment by awalkowiak** [comment]
@meenupant @EnriqueCorado at this point there is no "Approval" of records and no email is being sent. If user is claiming something, then it's cloned into his records (and is shown/visible right away).

In the ticket that @EnriqueCorado linked there will be checking if the records are dirty (as it was discussed during the last standup call) and if users will have incomplete data it will be highlighted in some way (and record won't be visible for others beside claiming user until it gets fixed).

**Comment by johnhbenetech** [comment]
@meenupant Unfortunately this may have been one of those tasks where too many requirements were scattered in too many places. Hopefully the new templates can help prevent this going forward. Depending on how critical the missed functionality is for the pilot - let's make sure the tasks referred to above make it over to dev ASAP for the next milestone.
