### ISSUE TITLE
Reset Password Email existence check

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1560]
User Story (encompasses persona, purpose, value) - e.g. As a [persona] i want to be able to [purpose] so that I can [value]:

As a user resetting my password I want to know if the email I am inputting is an email associated with Service Net. If the email doesn't exist on the platform I would like to know so I input a different email 

Description:

Add a check on the email field when a user tries to reset their password to see if the email inputted exists in the database. 
- if the email doesn't exist make the email header red
- add a red box around the text entry field 
- add the following message below the text entry field
- "The email you provided is not associated with an active Service Net Account."

Scope (includes UI mockups, user flow, and out of scope):

<img width="885" alt="Screenshot 2021-01-08 095912" src="https://user-images.githubusercontent.com/65787629/104048616-623d5e80-5198-11eb-82b7-a176d4088b44.png">

Acceptance criteria (includes edge cases):
*

Dependencies (links to other related tasks):
*

Any required analytics for task:
*

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [ ] Passes Acceptance Criteria
- [ ] All bug reports fixed/merged/tested
- [ ] Regression test cases cycle updated if needed

Product Signoff
- [ ] Approved for release

**Comment by johnhbenetech** [comment]
@EnriqueCorado sending this back to product scoping. General security best practices are to make authentication flows zero-knowledge for potential attackers. For example, you will commonly see a post reset message like "If this address exists in our system, you will receive a reset email"

The reasoning behind this is you should make it as difficult as possible for an attacker. If we implement this task they no longer have to 'guess' if an email is on the system, since this will confirm this for them. This would also potentially allow for an attacker to make 1000s of calls to this page to weed out addresses in our system. I would advise against this task for those reasons

**Comment by EnriqueCorado** [comment]
@johnhbenetech understood thank you for the quick feedback. i will close this issue
