### ISSUE TITLE
Remove get session call when user is logged out

### ISSUE THREAD

**Issue by wojtekbu** [benetech/ServiceNet#233]
There is some unnecessary request being done after the user is logging out, which results in 401, however, the error is only visible in the console. The same thing is happening when you refresh the home page not being logged in.

Acceptance criteria:
- there should be no getSession/getAccount call when the user is logged out,
- reloading the page shouldn't log out the user.

**Comment by kkaczmarczyk** [comment]
It appears getSession request is being sent in JHipster this way so that CSRF token is fetched and set with 'set-cookie' header in the response. That way there is no need to refresh the whole webpage to set CSRF token (as it is done on initial load), but it can be done asynchronously. This requires further investigation for the workaround.

**Comment by johnhbenetech** [comment]
@awalkowiak closing this as I believe it's the same as #1157
