### ISSUE TITLE
Search doesn't always show results

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#288]
Sometimes I'll enter a search term (that i know has results). The pagination counter will show 0/13 (in the case of 13 matches) but no records will show.

If you use any sort, the records will show as expected. Once this happens, the results start showing for either sort (until you clear search).

I can't figure out in which scenarios this happens. There's no log output. Here's a video:
https://drive.google.com/file/d/1S7mC-uJhoVQqvy62LVFIwIwyDC-6RHAB/view

**Comment by wojtekbu** [comment]
@johnhbenetech I have followed the steps from the video, but I couldn't reproduce the 'Search doesn't always show results' #288. Could you send me database dumps of Postgresql and MongoDB? It would be very helpful.

**Comment by johnhbenetech** [comment]
I can't reliably reproduce. It happens once here and there. I'll move this to the backlog to see if I can get it to more reliably reproduce.

**Comment by johnhbenetech** [comment]
QA, can you look at this issue and see if you are able to track it down? We've had a few users report it, but I've used the same search term on the same data and have seen it but then cant reproduce again using the same actions.

**Comment by kkrawczyk123** [comment]
Unfortunately, I was not able to reproduce the issue. I've tried on Chrome, Firefox, Safari and Edge. @johnhbenetech should I close it for now?

**Comment by johnhbenetech** [comment]
@kkaczmarczyk Still happening for me on dev server. I can't crack the pattern - it's definitely something during the delay before displaying records.

https://drive.google.com/file/d/1Byu9GOgVUYsCq5eZauXD5v3zpmc8Afb3/view

log into uwbauser on dev, search for 'health' then search for 'health s'
 you may also try searching for 'health', scrolling down so a second page of results loads, then changing it to 'health s'

**Comment by kkrawczyk123** [comment]
@johnhbenetech I have tried on dev server and uwbauser and I have noticed that it happens when loading of the searched records is interrupted somehow like clicking elsewhere after input not a whole word or scroll immediately after input some letters in a search field. It was difficult to reproduce it, especially for the first time. I have identified cases like: 
1) When searching for a phrase composed of more than one word and there is more than one page of the results. I input the first word, scroll down the page for more than one page of the results will load. I go back to the search field and when start to input the second word I saw the empty page with results like 0/13.
I do not fully understand how but after this action I was able to reproduce it in scenarios like:
2) I started to input some letters and click very fast elsewhere before they started to load.
3) I started to input some word and scroll the page before some suggested results will show up.
Additionally, I was not able to perform scenario 2 and 3 right after signing in to the service net.
I am attaching the gif of my actions.
![Peek 2019-05-10 16-21](https://user-images.githubusercontent.com/33342488/57535082-cb285f80-7341-11e9-85cf-ba8fa7f2eacd.gif)
 I hope that this informations will be helpful for identifying the cause. I am moving the issue to the Up Next column for developers.

**Comment by bognasoldev89** [comment]
@johnhbenetech I am not sure if we are talking about the same case, but logged as hluser I was trying to find International Institute of the Bay Area (IIBA) and search couldn't find it (with 0/6 on progress bar). I found this organisation manually by scrolling down though, so it's on the list for sure.

![Screenshot from 2019-06-18 16-33-49](https://user-images.githubusercontent.com/51324797/59693255-e3b05300-91e6-11e9-82f8-2c168f8fbd8a.png)

**Comment by johnhbenetech** [comment]
Yes that's the same, if you try sorting I believe it should then show correctly.

If this is still happening after the query refactor, then I think it has to be on the frontend

**Comment by johnhbenetech** [comment]
out of date
