### ISSUE TITLE
Matching question and answer(s)

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#294]
-	Revise the language of the question
-	Keep the red button. Delete the green one (Clotilde and Laura/ John - ok)

**Comment by CloVasco** [comment]
Alex feedback on that when he first saw the platform- "Keeping the “this record is bad button” but take away this record is good button. Allowing people to give feedback and help the algorithm (also posits it as a bad record not a bad program). Rather than this record is good, see if people copied over they information and can understand that to be a good match

**Comment by laurabenetech** [comment]
@CloVasco Here are 2 options for the revised text with the green button removed. Option 1: Button says: "Yes, remove this record." Advantage: users might be more likely to click the red button if they know their action is going to remove the record. Disadvantage: Removal doesn't happen immediately. Option 2: Button says "Yes, this is a mismatch" Advantage: IDs it as a mismatch. Disadvantage: Users might be less likely to click? Let me know if you'd like to discuss since this messaging is tricky to get right.
<img width="388" alt="Mismatch Remove Record" src="https://user-images.githubusercontent.com/48697326/54947152-e0af0a80-4ef6-11e9-9464-4a90abafe361.png">
<img width="388" alt="Mismatch button" src="https://user-images.githubusercontent.com/48697326/54947174-ec9acc80-4ef6-11e9-8c10-2cda61a0544e.png">

**Comment by CloVasco** [comment]
Thanks @laurabenetech 
I prefer option 1, provided that we can include the dismissal of records when they are not a good match in the same sprint, which would be great! - to be discussed with John on Wednesday.
Over to you @johnhbenetech

**Comment by laurabenetech** [comment]
@CloVasco Here is the finalized version with the view removed records link.
![mismatch_with_link_4_8_19](https://user-images.githubusercontent.com/48697326/55750595-7b7c0e80-59f8-11e9-8b5c-56173a91b600.png)

**Comment by CloVasco** [comment]
@johnhbenetech Here is the new visual. 
I have copied it in https://github.com/benetech/ServiceNet/issues/339 that's a related task

**Comment by kkrawczyk123** [comment]
Confirmed that the green button has been removed, the text has been changed to "Is this partner record a mismatch (a totally different organization)?" and text on the red button is "Yes, Remove this record"
