### ISSUE TITLE
"tks for your feebdack" message (matching)

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#330]

**Comment by laurabenetech** [comment]
@CloVasco Here is the confirmation  dialog. I added a note to let users know this removal will happen in an upcoming update (rather than immediately).
<img width="324" alt="Mismatch Feedback dialog" src="https://user-images.githubusercontent.com/48697326/54947291-32f02b80-4ef7-11e9-915d-1431868899f5.png">

**Comment by CloVasco** [comment]
Thanks @laurabenetech 
Ok for the main text. 
Similarly to the matching question/red button language, we may not need the note if we can include the dismissal of non matching records in the same sprint. To be discussed with @johnhbenetech on Wednesday
@johnhbenetech - quick question - if we allow users to dismiss a record that's not a good match, it will be removed immediately, am I right? no need to wait 24h or until the next SN update for it to disappear? because if there is a lag, we'll definitely need a note in this confirmation dialog to tell them!

**Comment by johnhbenetech** [comment]
I think it can be removed quickly. I think its safest to do it where it wont show up the next time they view the record (or when they refresh).

**Comment by CloVasco** [comment]
Closed this issue as we are tackling it in tasks https://github.com/benetech/ServiceNet/issues/339  and https://github.com/benetech/ServiceNet/issues/294
