### ISSUE TITLE
Add "go back to top" button

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#367]
Add a button to go back to top of the page on pages:
- single record view
-side by side view

**Comment by CloVasco** [comment]
@laurabenetech could you please provide the visual? thanks in advance

**Comment by laurabenetech** [comment]
@CloVasco 
The Back to Top button appears in the lower right-hand corner of the screen after the user has scrolled downwards so that they no longer see the top of the screen (Org Details section).

<img width="94" alt="Back to Top button" src="https://user-images.githubusercontent.com/48697326/57555341-e044c480-7328-11e9-8352-f348a8241363.png">

Once the user has scrolled down or is scrolling, the button persists in the bottom righthand corner of the screen so that the user can easily click the button anytime to return to the top. Once user clicks the button and returns to the top, the button disappears.

@johnhbenetech  I’m not sure how to technically describe when this should appear. If it makes sense to do this in terms of number of seconds of downward scrolling or after the user has reached the point where the Locations section is at the top of the screen, we can do that. I just want to ensure that the button doesn’t appear immediately if users do a small amount of scrolling (but are still viewing that first screen of info—the Org Details).

**Comment by CloVasco** [comment]
@laurabenetech 
thanks. Over to you, @johnhbenetech

**Comment by mariaogryczak** [comment]
@johnhbenetech 
Do you have any specific requirements connected with this button? I mean:
after how much scrolling should it appear?
how fast should it scroll up to the top?

Moreover, is the "side by side view" the "multi record view" or is it something else?

**Comment by johnhbenetech** [comment]
@mariaogryczak 

Yes side-by-side = multi record view

With regards to behavior. This library seems to perform how I would want it:
https://www.npmjs.com/package/react-scroll-up-button

Button appears after a small amount of scrolling. Clicking button smooth scrolls back to top. We would just need to replace the button with the design from above.

**Comment by bognasoldev89** [comment]
Confirmed that button exists and works perfectly fine
