### ISSUE TITLE
Fix size of fields

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#378]
To make sure user can easily read what's in a field. Arantxa told Clotilde about this problem during my end-of -March call + we saw this during our training: sometimes the text is super long, the size of the box is too small and it's not possible to drag the box down to make it bigger (for instance, not possible to do for the eligibility field)

**Comment by johnhbenetech** [comment]
Seems to just be Eligibility thats needs the expanding text box added for now

**Comment by bognasoldev89** [comment]
The issue was tested on Chrome and Mozilla Firefox and works on both browsers.

Screenshots below show fields fixed in this issue and earlier on FF:
![Screenshot from 2019-07-30 13-32-51](https://user-images.githubusercontent.com/51324797/62125909-bdde9980-b2ce-11e9-8f8c-588d48decfa1.png)

And Chrome:
![Screenshot from 2019-07-30 13-35-58](https://user-images.githubusercontent.com/51324797/62125993-fda58100-b2ce-11e9-86ee-d0611fda21d7.png)
