### ISSUE TITLE
Investigate long delays before conflict detection starts after data upload

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#474]

**Comment by jkondrat** [comment]
@johnhbenetech It turned out that the delay is caused by poor performance of conflict detection. I have improved logging in organization match service, we have two async methods - the first one being createOrUpdateOrganizationMatches (for each uploaded organization, I believe we have around 2000 of them in ShelterTech). At the end of this method, it calls another Async method that detects conflicts and it's put at the end of the queue - that's why it starts after a couple hours. If we wanted conflict detection to run immediately, we could create another queue, but that wouldn't help with performance

I think we should just work on #542 and see if we can simplify these methods and optimize the queries

**Comment by johnhbenetech** [comment]
@jkondrat Yes I think focusing on #542 is the right choice here. It's just good to know that the matching algorithm is the largest driver of the delay at this point.

You probably know way more than me at this point, but my understanding was the geo matching was one of the largest drivers of poor performance in the matching algorithm. You might already be aware of this, but check out this commit:

https://github.com/benetech/ServiceNet/commit/acc10398cb61651fb2a869000d946b5f4f954062

I forget exactly what it does - my gut says that it doesn't look for matches if there are no locations within X miles in common between orgs.

With the new structured geocode results it might be possible to come up with multiple approaches of filtering out pairs that don't need further inspection.

I can also imagine looking for where we might further index the database.
