### ISSUE TITLE
Issue with Discovery feature - records not in your own database

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#665]
This item https://github.com/benetech/ServiceNet/issues/440 appears to work really well, I just found a weird edge case that I think is an issue.

Sign in with the uwbauser account. Search for the organization "Housing Authority of the County of Contra Costa" and ensure the "Only show matching" is checked and you will get no results. 

If you uncheck the "Only show matching" box, you do get results as there is an exact match to that name in the healthleads database, and it shows in the primary left-side column. 

However, there is a matching record in the UWBA database, so this result should have shown in the initial search, where "Only show matching" is checked. It has a match, just with a conflicting name from what was searched.

I thought further about whether that UWBA record should have occupied the left column, but I don't think so, I think it is correct to have the record that exactly matches the search be the one in the left column, for consistency.

![Capture](https://user-images.githubusercontent.com/52297301/63896427-d235b500-c9a6-11e9-8194-0d1c2c2f694c.PNG)

**Comment by johnhbenetech** [comment]
@bognasoldev89 Can you look into this one as well

**Comment by johnhbenetech** [comment]
Copying comments from an email chain:

Just a hunch, but I’m guessing:

•	You search for your record name if ‘only show matching’ is checked
•	If ‘only show matching’ is unchecked, you can now search for records **not already matching** one of your records.

Therefore any partner record you already have a match with is invisible to the search and filter, because your version of the record takes priority.


I think the solution is one of two:

1.	Have search and filter look at not only the main record, but also at the complete set of matching records as a single searchable/filterable blob. This has a performance hit, but shouldn’t be too bad. I think the worse part is that someone could be looking for one of their records by org name, and they keep getting cards that don’t clearly match (because the search matched on one of the partner records not visible until the click in and flip to it).

2.	When ‘only show matching’ is NOT clicked, we show:
* All of your records with matches
* All of your records without matches
* All partner records (even if you already have a match with that record)

This  of course means that a record will appear twice, once at the top level and once within another record’s side by side.

**Comment by bognasoldev89** [comment]
@johnhbenetech @NeilMBenetech 
I'm not sure I fully understand this case.

I found mentioned record and, as far as I understand how searching and filtering features work, it is displayed correctly in my opinion.

UWBA record matched to healthleads record has a different name hence it won't show after searching for "Housing Authority of the County of Contra Costa" while Only show matching is checked (it's named "HOUSING AUTHORITY OF THE COUNTY OF Commoncounty (ABCD)"):
![Screenshot from 2019-08-29 14-18-52](https://user-images.githubusercontent.com/51324797/63939620-f4433c00-ca67-11e9-93d2-3ee391edae9c.png)


> I thought further about whether that UWBA record should have occupied the left column, but I don't think so, I think it is correct to have the record that exactly matches the search be the one in the left column, for consistency.
I'm a little confused. From this, I understand that record from your screenshot is displayed correctly in your opinion too. Please, correct me, if I'm wrong.

**Comment by johnhbenetech** [comment]
The crux of the issue is try searching for "commoncounty". Nothing shows up even when you uncheck only show matching (despite us knowing the record exists because we see it in the side by side view).

My understanding is that the reason it doesn't show up is because it already matches one of your records, and so your version on the record takes priority in search and filtering.

Neil's request is to figure out some way where searching for commoncounty still lets you know that there is a record in the partner system

**Comment by bognasoldev89** [comment]
@johnhbenetech I searched for "commoncounty" and I see results, with and without Only show matching checkbox. It is what you were looking for, right?

![Screenshot from 2019-08-29 15-30-24](https://user-images.githubusercontent.com/51324797/63944682-4d17d200-ca72-11e9-8a8f-c457a3bd786c.png)
![Screenshot from 2019-08-29 15-30-36](https://user-images.githubusercontent.com/51324797/63944683-4db06880-ca72-11e9-8f38-b2e051c5e6a1.png)

**Comment by johnhbenetech** [comment]
I removed previous comments for clarity (i gave a bad example!) Here is a better example hopefully:

Log in as healthleads user, search for 'Senior Coastsider' with 'only show matching' on:
![image](https://user-images.githubusercontent.com/12927553/63951487-74a37600-ca43-11e9-944a-0a67bebdcf70.png)

When you click in and flip the side-by-side you see this record from SMC:
![image](https://user-images.githubusercontent.com/12927553/63951545-8e44bd80-ca43-11e9-850e-b3b279f9ce9c.png)

Now return to the main page. Turn 'only matching records' off. Search for 'Lesley' - nothing returns:
![image](https://user-images.githubusercontent.com/12927553/63951631-b6ccb780-ca43-11e9-9650-614a0d8245c4.png)

Please look into the proposals in my previous comments and let me know if you recommend one of those approaches and any additional concerns you may have.

**Comment by jkondrat** [comment]
Hi @johnhbenetech : I think that both of proposed solutions would work well, but the first one in fact could cause confusion and it's worth checking if there's a performance hit. The question is, would it be a problem for the users if a record appears twice, once at the top and once as a partner's match?

**Comment by johnhbenetech** [comment]
@NeilMBenetech Would the record showing twice be ok to start? I think you may have had a slightly different recommendation

**Comment by NeilMBenetech** [comment]
Thanks for asking @johnhbenetech . Yes here's my alternative idea, what do you think? What if, where we note the conflicts, we indicate the name that was hit by the search, when it is different than the “base” record’s name? A little more cognitive load but at least the users should readily know to look over there when the main name doesn’t match.

**Comment by bognasoldev89** [comment]
@johnhbenetech I tried a few configurations and I think it works good now. I always got what I was searching for.

For example, logged as hluser I got San Francisco Department of Public Health:

![665 1](https://user-images.githubusercontent.com/51324797/67378640-dbe32f80-f587-11e9-93e0-be3242f19cbc.png)

It is matched with Human Services (WIC) from ShelterTech provider:

![665 2](https://user-images.githubusercontent.com/51324797/67378479-9c1c4800-f587-11e9-87cb-8f147a5d1d6a.png)

And I was able to find this organization:

![665 3](https://user-images.githubusercontent.com/51324797/67378502-a9393700-f587-11e9-8396-d687565530aa.png)
