### ISSUE TITLE
Change taxonomy filter to 'OR' instead of 'AND' logic

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#668]
Let me know if i misunderstood what was discussed on the call today.

Ideally the taxonomy filter would function as an OR - meaning any organizations with services that match ANY of the defined taxonomies would return.

@NeilMBenetech please confirm that you agree with this.

**Comment by NeilMBenetech** [comment]
@johnhbenetech Yes that's what makes most sense to me. Especially because there are variations in categories you must be getting from the partners. For example the official taxonomy has a base term called "Food Pantries" but the auto-suggest also returns "Food Pantry". So by OR'ing these together you can get all of them.

When/if we decide to implement more complex handling of the taxonomy we'll probably want to let the user choose between AND and OR. But this is a tiny consideration amongst many other complexities about the taxonomy.

**Comment by jkondrat** [comment]
Hi @johnhbenetech : it looks that the taxonomy filter already works this way - I selected "Money management" and "Childcare" and got results that had either of those.

**Comment by bognasoldev89** [comment]
> Hi @johnhbenetech : it looks that the taxonomy filter already works this way - I selected "Money management" and "Childcare" and got results that had either of those.

I have to agree with @jkondrat, it looks like it is OR filter.
