### ISSUE TITLE
Match records at the Location level

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#698]
Since we are geocoding the locations, we should be able to reliably indicate a "match" between a user's and the given partner's Location records. 

I propose that when you select one of your own Location records, you have the option to express that you want the partner location records to automatically rotate to the one(s) that match your own selected Location record. 

Perhaps we have a "link" icon (like a chain link) with a checkbox next to it with a tooltip that says : "Whenever I select a Location record, show me this partner's matching Location record, if available." 

The "link" icon  is disabled and deselected by default but enabled when the selected record has a match to the partner's location record. When you click it, then it immediately selects the partner's matching Location record for you. 

If you change your own Location record and the "link" is still selected, it will automatically change to the partner's matching Location record. But if your newly-selected Location record does not have a match, the "link" icon will deselect and become disabled.

**Comment by NeilMBenetech** [comment]
Hi @johnhbenetech not sure which dev to target on this one but some feedback... I am logged into the UWBA system on the staging server and working with this record: https://benetechservicenet.org/#/multi-record-view/a73a3cd8-2f26-4083-8d41-c29de6999899

1. Not intuitive that the "link" icon has a checkbox above it and needs to be clicked on. Could we change it so that if you click on the "link" icon it also selects thee checkbox?

2. When I select the "link" icon and choose a selection from a list, it may or may not properly match to a Location on the other column (see further issues below) but either way it de-selects the "link" icon. It should stay selected until I manually de-select it.

3. When I choose an item in the first position of the <select> list on the left hand side (Locations), with the "link" icon selected, it automatically selects the item in the first position on the right hand side, even though that is not a matching Location.

4. When I choose a Location in the left side with the "link" icon selected, that I know has a match to a Location on the right side, it correctly populates that Location on the right side - but the <select> list has not been changed to reflect the newly-selected Location. Example : 2850 North First Street San Jose

5. With the "link" icon selected, I choose an item on the right side that I know has a match on the left side (851 Trager Avenue San Bruno). However the right side does not update to reflect the new selection and the left side  also does not change.

I'll stop testing for now as I can't get past these issues to test more deeply.

**Comment by bognasoldev89** [comment]
@jkondrat I am not sure if an issue I discovered is linked to this one but I suppose it can be.
While opening organization's detail page in the new tab it works fine, but while opening it in the same tab, unexpected error occurs:
![displaying record view](https://user-images.githubusercontent.com/51324797/69044137-adc10600-09f4-11ea-8e64-997dd8197062.gif)

I also noticed that checkbox sometimes de-selects itself.

Can you please investigate?

**Comment by jkondrat** [comment]
@bognasoldev89 it turns out that physical address is null for some locations. This is not related to my changes, ould you please create a bug?

**Comment by johnhbenetech** [comment]
I've broken out the null physical location issue into #746

**Comment by bognasoldev89** [comment]
@jkondrat I found an organization and its match has a Location at the exact same place (even longitude and latitude) and it's not rotated to it:

![easterseals bay area](https://user-images.githubusercontent.com/51324797/71181579-b36c6e80-2274-11ea-826c-7b52ec70f674.png)

![easterseals bay area](https://user-images.githubusercontent.com/51324797/71181655-e151b300-2274-11ea-9481-bbf716546b24.gif)

Link to records from screens: https://benetechservicenet.org/#/multi-record-view/13e502f8-03e7-40eb-a876-3f3ba6f09228

@jkondrat can you please investigate further?

**Comment by bognasoldev89** [comment]
In my opinion, all issues are now resolved.

Here are examples from mentioned organizations, locations are matched correctly now:

![698 working 1](https://user-images.githubusercontent.com/51324797/71967344-81ab4f80-3203-11ea-830c-43e476e37445.gif)

![698 working 2](https://user-images.githubusercontent.com/51324797/71967345-8243e600-3203-11ea-9f34-6f396407e692.gif)

**Comment by NeilMBenetech** [comment]
@bognasoldev89 Can you give me an example Organization or two please that contain Locations that match to at least one partner Organization? I've tried almost 10 and none of them yet have any matching Locations, at least in Staging.

**Comment by johnhbenetech** [comment]
Something funky is going on here. I can't seem to always reproduce Bogna's results on staging. This could be due to a recent code change or the database migration. I did some SQL to find locations that have location_match defined and put some examples below. 

@bognasoldev89 Can you recheck on staging and follow-up witht he team on what might be happening?


MISSION NEIGHBORHOOD RESOURCE CENTER
Clerk of the San Francisco Superior Court - Default Unit
US Citizenship and Immigration Services (USCIS) - San Francisco Field Office
Plaza Adelante Digital Opportunity Center
SAN FRANCISCO OFFICE OF ECONOMIC AND WORKFORCE DEVELOPMENT

**Comment by bognasoldev89** [comment]
@johnhbenetech I checked Organizations mentioned and:
- MISSION NEIGHBORHOOD RESOURCE CENTER  - I couldn't find this organization, but I found MISSION NEIGHBORHOOD HEALTH CENTER. Anyway, I checked it and something is going on here indeed. While I know two organizations have Locations at 165 Capp Street San Francisco, it's not rotated to it:

![698 1](https://user-images.githubusercontent.com/51324797/73356549-e99d0500-429a-11ea-810e-76e85f0a37e7.gif)

- Clerk of the San Francisco Superior Court - Default Unit  - all of the Locations have the same address so I'm not sure how to proceed in this case because it seems fine to me.

- US Citizenship and Immigration Services (USCIS) - San Francisco Field Office  - I have only one hit with completely different Location

- Plaza Adelante Digital Opportunity Center  - I have only one hit with the same Location so it's matched anyway, by default

- SAN FRANCISCO OFFICE OF ECONOMIC AND WORKFORCE DEVELOPMENT  - yes, in this case Locations don't rotate to matched one.

I rechecked this issue on Organizations I used previously and it doesn't work as it did before.

cc: @jkondrat
