### ISSUE TITLE
Pages used by previous user available by "Back" button for current user

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#792]
Reproduction steps:
1. Log in as a user (for example edenuser)
2. Go through some pages, organizations, changing password, etc
3. Log out and log in as a different user (for example admin, stuser)
4. Click "< Back" button a few times

Expected result:
5. User has no access to the pages used by the previous user

Actual result:
5. User has access to the pages used by the previous user, but with his data.

@johnhbenetech I added this bug to Up Next column because I think it's really important from safety point of view.

Exemplary gif:
![bug 792](https://user-images.githubusercontent.com/51324797/73167900-0568a580-40f9-11ea-8dc2-c78ee94f92ff.gif)

**Comment by awalkowiak** [comment]
Dev note for who will be working on it:
I thought that maybe clearing/resetting this.props.history on logout might help, but this solution probably is not trivial due https://github.com/ReactTraining/history/issues/567#issuecomment-386323573 (I tried suggested window reloading, but it was not helping in our case)

**Comment by kdondziak** [comment]
I my opinion it's work as it should be, because user could check browser history and 'spy' in that way. Since #810 is solved there are no security issues related to unauthorized access. One solution to this would be adding some identifier (e.g. login) to url and check on backend if it's login of current user. If not then show unauthorized page. @awalkowiak @jkondrat Please give your opinion.

**Comment by jkondrat** [comment]
I agree with @kdondziak

**Comment by awalkowiak** [comment]
Yup, browser has the same behavior. We have now secured actions for users without admin role, so i guess we could close this one.
@johnhbenetech whats your opinion on this one? Can we close this?

**Comment by awalkowiak** [comment]
As discussed on call, I am closing this one.
