### ISSUE TITLE
"About" description needs to be updated for Sacramento partners

### ISSUE THREAD

**Issue by alexrcabral** [benetech/ServiceNet#831]
The "About" link accessed through the Sacramento pilot leads only to information about the Bay Area pilot. This needs to be updated to be more general information, so as not to confused Sacramento pilot partners. 

https://servicenet.benetech.org/#/about-us

**Comment by johnhbenetech** [comment]
We'll need the copy/formating for this

**Comment by alexrcabral** [comment]
@NeilMBenetech 
Do we have official copy from press releases or from marketing on how we want to present Service Net as a whole? This is accessed both by Bay Area partners as well as Sacramento partners, so the framing is sensitive.

**Comment by NeilMBenetech** [comment]
HI @alexrcabral I haven't written any copy for the public website. If you want that web page to be reflective of the Sacramento pilot as well it pretty much needs to be rewritten. Since it is a publc-facing website, I recommend that we do get someone from marketing involved. I can start an email thread with Joel Riciputi - he may delegate or he may say he's fine with us doing our own prose.
