### ISSUE TITLE
Feedback button

### ISSUE THREAD

**Issue by alexrcabral** [benetech/ServiceNet#832]
Feedback button should be created at the top of the page, located to the right of the "About" link. 

<img width="1136" alt="screenshot showing addition of link named feedback" src="https://user-images.githubusercontent.com/47576069/74199949-74c2b700-4c1a-11ea-9193-b320497a47b3.png">

This should open a small menu with the title "Feedback" and the option to send a message. The prompt should read: "Send us your question or suggestion..." 

<img alt="mockup showing the header Feedback over a box for input and a box for an optional email, followed by a submit feedback button" src="https://user-images.githubusercontent.com/47576069/74200760-9de44700-4c1c-11ea-8281-46d0483fe640.png">

This will also require a new distribution email be created for the feedback.

**Comment by alexrcabral** [comment]
@NeilMBenetech let me know if there's anything else you need in the specifications for the feedback button

**Comment by NeilMBenetech** [comment]
@alexrcabral looks good to me. For now I propose that feedback@benetech.org (might need something more Service Net specific?) goes to Alex, Neil and John.

**Comment by johnhbenetech** [comment]
Here's the task we discussed on the call. Let's get started on the front end components. There are several additional requirements with this task.

* Enable email (i assume using the built in jhipster config)
* Add to be provided API keys and URL for mail service to env vars and add to deployment scripts. I believe jhipster has these already?
* Disable the sending of an activation email upon user registration. Currently this doesnt work because email isnt set up. After this task we still want this not to work so users must be approved manually.

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on Chrome browser 79.0.3945.130

Verified cases:
- Clicking "Feedback" as a sacramentouser
- Sending message

@johnhbenetech confirmed that message was delivered.
Feedback is not available for different types of users

**Attachments**

![832 1](https://user-images.githubusercontent.com/51324797/76554284-e69a5480-6495-11ea-8277-1942f3f7eb82.png)

![832 2](https://user-images.githubusercontent.com/51324797/76554287-e7cb8180-6495-11ea-89c2-e52d748b0026.png)
