### ISSUE TITLE
Should we reset filter on login?

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#838]
Interested to get the team's input as well as @neilmbenetech

I've noticed in a few cases where I login and am presented with no results. I only get results after hitting the reset filter button.

Additionally sometimes after new filter-related feature release i experience similar issues. Would it make sense just to automatically reset the filter after a login?

@neilmbenetech do you see a user need to maintain a filter setting across sessions (seeing as we have save filter feature)?

**Comment by NeilMBenetech** [comment]
@johnhbenetech I agree that the filter should be reset upon login. Confusing otherwise.

**Comment by bognasoldev89** [comment]
So filters are now resetting right after logging in, by admin and regular users. In my opinion, this issue is resolved.

Examples:

![838 admin](https://user-images.githubusercontent.com/51324797/74945006-49e51980-53f7-11ea-97b7-71cea18f0b20.gif)

![838 hluser](https://user-images.githubusercontent.com/51324797/74945012-4baedd00-53f7-11ea-8737-3ddccafc67af.gif)

![838 laacuser](https://user-images.githubusercontent.com/51324797/74945013-4baedd00-53f7-11ea-88a1-b3dd81a18278.gif)
