### ISSUE TITLE
Reinstitute free text search

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#875]
Correct me if I'm wrong, but with the autocomplete work it appears you can no longer do a free text search (if you don't pick one of the autocomplete options for instance).

It seems like this renders the "search fields" option irrelevant because you can't actually enter text to search.

Is it possible to bring free text search back for when you don't do an autocomplete?

**Comment by kdondziak** [comment]
@johnhbenetech I assume that we are discussing only 'Search for organization, leave blank...'
 behaviour. Autocomplete works but it's unintuitive. You can write free text there but if you press enter, the first matching option will be selected (e.g. type 'hospita' -> press enter -> 'Nepa state hospital' is selected). In order to use free text search you need to type something and click apply.
Bogna's suggestion is to change behaviour when enter is pressed. (e.g. type 'hospita' -> press enter -> app behave like apply button was clicked -> all organization with 'hospita' within name is showed)

**Comment by johnhbenetech** [comment]
@kdondziak The proposed solution is fine.

I still don't think it works as you describe though. Even after typing in text, the apply button is still grayed out, and therefore can't be clicked. Even if I change a filter to make apply clickable, it doesn't respect the entered text for organization search (nor does it work for all the combinations of organization/service/location search within fields)

**Comment by kdondziak** [comment]
@johnhbenetech "Even after typing in text, the apply button is still grayed out, and therefore can't be clicked" This is another issue that need to be resolved. Can you try type something and click reset button?

**Comment by johnhbenetech** [comment]
@kdondziak that works for the organization name search, but I can't choose which entity and fields to search since reset always puts it back to org.

So right now there doesn't seem to be a away to do free text searching of anything but org name and alternate name

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on Chrome browser v79.0.3945.130

**Verified cases**
- performing search for popular phrases for default settings
- performing search for Services fields
- performing search for Locations fields
- performing search for no fields
- performing search with auto-suggest for Orgs and Services
- changing search fields after search

**Summary**
Free text search was available before, but it was highly intuitive (it needed Apply button and, due to activate this button, changes in filtering had to be made). At this moment the Enter key allows user to search through chosen fields.

**Attachments**
One provider, Name/Alternate Name search:

![875 one provider name](https://user-images.githubusercontent.com/51324797/77406846-8d93c000-6db5-11ea-9895-7a51b1db5d9a.gif)

All of the providers, Locations field search:

![875 more providers location thing](https://user-images.githubusercontent.com/51324797/77406948-b1570600-6db5-11ea-9a1d-91011b174cc1.gif)

**Comment by kdondziak** [comment]
Commit: https://github.com/benetech/ServiceNetGateway/commit/046a96f6a9ccd91acc9338f1a42da9300cbe973d
