### ISSUE TITLE
Regression testing after re-architecture

### ISSUE THREAD

**Issue by bognasoldev89** [benetech/ServiceNet#880]
After re-architecture of the ServiceNet it is important to check thoroughly if every functionality and feature works as expected.

The regression test suite contains all tests designed for this moment.
Link for test suite:
https://docs.google.com/spreadsheets/d/1VzIrGaAPjOJHqyoaqSFpfaqrB_UGd1wUTQM8YfHHnVU/edit?usp=sharing

**ACC**
- All test cases from the list are performed
- Report is created
- Tickets for found bugs are created and linked in the report and this issue

**Comment by abaranowska1** [comment]
**Regression testing status report**
Regression testing on 4 browsers (Google Chrome, Mozilla Firefox, MS Edge, Safari) is finished.
**List of reported issues:**

- https://github.com/benetech/ServiceNet/issues/895 - DONE
- https://github.com/benetech/ServiceNet/issues/894 - DONE
- https://github.com/benetech/ServiceNet/issues/897
- https://github.com/benetech/ServiceNet/issues/795
- https://github.com/benetech/ServiceNet/issues/896
- https://github.com/benetech/ServiceNet/issues/898
- https://github.com/benetech/ServiceNet/issues/899 - DONE
- https://github.com/benetech/ServiceNet/issues/901
- https://github.com/benetech/ServiceNet/issues/902
- https://github.com/benetech/ServiceNet/issues/906
- https://github.com/benetech/ServiceNet/issues/904 - DONE

**List of tested fixes/features during regression testing:**

- https://github.com/benetech/ServiceNet/issues/895 - Tested with success
- https://github.com/benetech/ServiceNet/issues/894 - Tested with success
- https://github.com/benetech/ServiceNet/issues/899 - Tested with success
- https://github.com/benetech/ServiceNet/issues/904 - Tested with success
- https://github.com/benetech/ServiceNet/issues/882 - Tested with success
- https://github.com/benetech/ServiceNet/issues/881 - Tested with success
- https://github.com/benetech/ServiceNet/issues/867 - Tested with success
- https://github.com/benetech/ServiceNet/issues/846 - Tested with success

**Summary:**

- Executed: 122 test cases - two test cases ( related to security ) were removed because they were out of date after re-architecture
- 115 test cases pass
- 7 test cases failed

Critical bugs are fixed. Regression testing after re-architecture is finished.
**Link to report:** https://docs.google.com/spreadsheets/d/1VzIrGaAPjOJHqyoaqSFpfaqrB_UGd1wUTQM8YfHHnVU/edit#gid=0
