### ISSUE TITLE
Ensure all activity filter use cases still working

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#886]
Refer to:

https://github.com/benetech/ServiceNet/issues/570

it appears 2 and 3 from that task must have been broken by a recent update.

**Comment by kdondziak** [comment]
@johnhbenetech I have a question about point 3. Is this how it should look for organizations without matches?
![image](https://user-images.githubusercontent.com/52406204/77519791-66ee8b80-6e80-11ea-8cff-02539bbbaf81.png)

**Comment by johnhbenetech** [comment]
I would add two things:

Add the partner name under the org name (since this isn't your data)

Some indication in the right side of 'no matches'

**Comment by kdondziak** [comment]
@johnhbenetech How do you like this
1. No matches and it is user's organization:
![image](https://user-images.githubusercontent.com/52406204/77640308-73dfad80-6f5a-11ea-87c9-a95c5efe3650.png)
2. No matches and it's partner organization:
![image](https://user-images.githubusercontent.com/52406204/77640392-970a5d00-6f5a-11ea-9222-da4de8b28de5.png)

**Comment by johnhbenetech** [comment]
@kdondziak works for me!

**Comment by kdondziak** [comment]
Gateway commit: https://github.com/benetech/ServiceNetGateway/commit/f86e90c1c7d687fe07bdeb5e6e1ae5d4e90fb75e

**Comment by abaranowska1** [comment]
**Verified on:**

- Google Chrome Version 80.0.3987.149, 
- Firefox Browser Version 74.0 

**Verified cases:**

- Records without matches show as they did previously

![0matches](https://user-images.githubusercontent.com/61964176/77653622-4271dc80-6f70-11ea-86c1-e889227ebcd7.gif)

- Records from a partner system that have no other matches are displayed in a view: single record view only, no side-by-side 
- Partner name is added under the organization name (since this isn't your data)
- Indication in the right side of 'no matches' is added 

![Selection_076](https://user-images.githubusercontent.com/61964176/77653608-3b4ace80-6f70-11ea-8702-c64e5de42422.png)
![Selection_077](https://user-images.githubusercontent.com/61964176/77653612-3e45bf00-6f70-11ea-971d-310dbbab1a2a.png)

Question: @johnhbenetech @kdondziak Now after login to the app records with 0 matches show on the top of the list - default sort is set to "Match Similatity - descending" - in my opinion, it doesn't look good, what do you think? 

![Selection_078](https://user-images.githubusercontent.com/61964176/77659290-2bcf8380-6f78-11ea-8978-476f2044b12b.png)

**Comment by abaranowska1** [comment]
**Tested with success**

**Verified on:**

- Google Chrome Version 80.0.3987.149,
- Firefox Browser Version 74.0

**Verified cases:**

- After login to the app records with 0 matches doesn't show on the top of the list
- Records without matches show as they did previously
- Records from a partner system that have no other matches are displayed in a view: single record view only, no side-by-side
- Partner name is added under the organization name (since this isn't your data)
- Indication in the right side of 'no matches' is added
