### ISSUE TITLE
Discover matches and conflicts for new Service Provide system account

### ISSUE THREAD

**Issue by awalkowiak** [benetech/ServiceNet#957]
Currently, the matches and conflicts for new users with the "Service Provider" system account are discovered between all other external service providers (UWBA, Eden, LAAC, etc). 
For the independent user with the "Service Provider" system account type, there should be checking for matches and conflicts with all other users with the same system account type.

(related issue: #931)

**Comment by johnhbenetech** [comment]
Right now the priority is to make UWBA, Eden, LAAC, etc aware of matching records from the individual accounts.

In the first version of the individual UI I don't plan to include any indication of matching records. Theoretically there shouldn't be any matches between the "Service Provider" records since a user is entering information only about the services they provide.

**Comment by awalkowiak** [comment]
@johnhbenetech Got it, then this ticket is redundant since the matching between individual accounts and other providers is working. Do we want to keep this ticket for the future? Or this can be closed for now?

**Comment by johnhbenetech** [comment]
@awalkowiak ill move it to the backlog in case we need it in the future
