### ISSUE TITLE
Staging no longer working on Firefox

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#994]
When trying to load staging on Firefox I get a bunch of npm/jhipster messages

sample:
An error has occured :-( Usual error causes You started the application from an IDE and you didn't run npm start or npm run webpack:build. You had a network error while running npm install. If you are behind a corporate proxy, it is likely that this error was caused by your proxy. Have a look at the JHipster error logs, you will probably have the cause of the error. You installed a Node.js version that doesn't work with JHipster: please use an LTS (long-term support) version, as it's the only version we support.

JS Console:
SyntaxError: invalid regexp group main.c75dedb71b526b1d9e0d.bundle.js:1:1

Chrome works fine

**Comment by kdondziak** [comment]
Solution on branch: https://github.com/benetech/ServiceNetGateway/commit/8900932fb4d578a214edf96d0fe49c795229f679

**Comment by bognasoldev89** [comment]
**Tested with success**

Verified on staging env, browsers:
- Firefox v76.0.1
- Edge v44.18362.449.0
- Safari v12.03.3

**Verified cases**
- Opening ServiceNet app on mentioned browsers
- Going through the app

**Summary**
Since this error occurred on Edge and Safari as well, I rechecked all of these browsers and went through the app a little. It's fine now.

**Attachment**
- Firefox example
![sn 994 ff](https://user-images.githubusercontent.com/51324797/82227054-8e655000-9927-11ea-95ec-5ec11fea9d55.gif)
